### ISSUE TITLE
Aparecer/ desaparecer texto

### ISSUE THREAD

**Issue by acanivano** [acanivano/acanivano.github.io#3]
@hhkaos
Hola Raúl. Quiero hacer una cosa con javascript y no sé por donde pillarlo.
Me gustaría aprovechar la barra Nav de Boostrap y en un botón que yo llame "Experiencia", me mostrara únicamente un nodo que tengo con información de mi experiencia, que solo apareciera ese texto, vaya.
Tengo dudas si lo puedo hacer con esto: http://getbootstrap.com/javascript/#tabs (Togglable tabs tab.js)
O hacerlo con html:  http://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp
Con getElement no puedo recuperar un href, verdad?
Gracias

**Comment by hhkaos** [comment]
Buenas crack,

Ahá, puedes usar un menú de pestañas para hacer eso sí. Los dos ejemplos que pasas son sobre lo mismo explicado en distintas páginas.

Primero tendrás que crear el contenido usando la estructura que te marca Bootstrap, por ejemplo: 

```html
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">...</div>
    <div role="tabpanel" class="tab-pane" id="profile">...</div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>

</div>
```

Que define todas las pestañas primero y luego todos los "**paneles**" con el contenido de cada pestaña.

Y luego con jQuery le defines el comportamiento:

```js
$('#myTabs a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
```

Este código básicamente lo que dice es que cada vez que se haga clic en un elemento HTML ```<a>``` que sea hijo de un elemento con ```id="myTabs"```, y esto último del "this" no lo vimos en clase por falta de tiempo (pero [aquí tienes un snippet](http://hhkaos.github.io/master-esri/codigo/js/?lesson=5&snippet=2) que a lo mejor te sirve), lo que quiere decir con ```$(this)``` es == "hacerme referecia a mi mismo" (el elemento que ha sido clicado). Por lo tanto lo que hace en este caso es invocar a la función ```tab()``` del elemento pulsado con el parámetro "show". Este comportamiento (función) lo añade Bootstrap a todos los "a" que representan las pestañas, y lo que hará esta función al ejecutarse será mostrar el elemento que tenga la ```class="tab-pane"``` y el id coincida con el que se indica en el ```href=""``` (lo mostrará porque inicialmente todos los "tab-pane" salvo el que tenga la clase "active" estarán ocultos).

Si te ha costado seguir la explicación intenta buscar algún tutorial en Youtube sobre "tab pane bootstrap" que como es tan popular seguro que hay muchos, [aquí tienes uno](https://www.youtube.com/watch?v=jxTu6hOipDM) (no lo he visto entero pero tenía buena pinta).

Un abrazo!

**Comment by acanivano** [comment]
Gracias @hhkaos !! ¿Podrías revisarme este código? No entiendo por qué no cambia de número. Lo he cogido del video que me recomendaste: hay muchos tutoriales de Boostrap!!! A este código no le pondré Javascript, pero le meteré alguna barrita de progreso o cosas por el estilo. 
Hoy hemos estado viendo la API de Javascript, estamos viendo todo lo que se puede hacer y FUAAAAA, la hostia!! Abrazo! 



<!DOCTYPE html>
<html lang="es">
		<head>
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link rel="stylesheet" href="css/reset.css">
			<link rel="stylesheet" href="css/main.css">
			<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
			<title>Mi curriculum</title>
			<link rel="shortcut icon" href="imagenes/favicon.ico">
			
		</head>
	<body>

	<div class = "col-md-12">
			<br/>

			<ul class="nav nav-tabs">
				<li class="nav-item">
					<a href="#about" class="nav-link active" role="tab" data toggle="tab">Alberto Cañivano</a>
				</li>
				
				<li class="nav-item">
					<a href="#experience" class="nav-link" role="tab" data toggle="tab">Experience</a>
				</li>

				<li class="nav-item">
					<a href="#projects" class="nav-link" role="tab" data toggle="tab">Projects</a>
				</li>

				<li class="nav-item">
					<a href="#education" class="nav-link" role="tab" data toggle="tab">Education</a>
				</li>
	
			</ul>
			

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade in active" id="about">1</div>
			<div role="tabpanel" class="tab-pane fade" id="experience">2</div>
			<div role="tabpanel" class="tab-pane fade" id="projects">3</div>
			<div role="tabpanel" class="tab-pane fade" id="education">4</div>
		</div>	

	</div>

	</body>

</html>

**Comment by hhkaos** [comment]
Hi crack, no has subido el código a Github, ¿no?

Estoy mirando:
* [https://acanivano.github.io](https://acanivano.github.io)
* [https://acanivano.github.io/index3.html](https://acanivano.github.io/index3.html)

Y en ninguno de los dos veo ese código.

Súbelo al repositorio, dime en cuál de los dos está y te ayudo desde ahí, ¿vale?.

Abrazo!
P.D: sep, la API la muuuucho juego ;P

**Comment by acanivano** [comment]
Buenas, lo he subido a Github, está en acanivanogithub.io/ToogleBar para mi
CV. Tengo que aprender a ordenar mi repo porque creo le empiezan a salir
gamusinos... Gracias tío!! Abrazo!

**Comment by hhkaos** [comment]
Lo miro n cto pueda crack. Mientras a lo mejor Andrea o algún otro compi a lo mejor puede echarte un ojo por aquí tb,no?

Ahora mismo voy n l coxe de camino a madrid

**Comment by acanivano** [comment]
Nada, no te preocupes. Ya lo he solucionado.
